name: Retrieve ACCESS_ID

on:
  push:
    branches:
      - main  # Runs workflow on push to main branch

jobs:
  print-access-id:
    runs-on: ubuntu-latest  # Use latest Ubuntu runner
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Print ACCESS_ID
        run: |
          echo "Checking GitHub Variables..."
          if [[ -z "${{ vars.ACCESS_ID }}" ]]; then
            echo "ERROR: ACCESS_ID is not set!"
            exit 1
          else
            echo "The ACCESS_ID is ${{ vars.ACCESS_ID }}"
          fi

