name: Access ID Workflow

on:
  push:
    branches:
      - main  # Change this if you're using a different branch

jobs:
  access-id-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Retrieve ACCESS_ID
        env:
          ACCESS_ID: ${{ vars.ACCESS_ID }}
        run: |
          echo "The ACCESS_ID is $ACCESS_ID"

