name: Secret Workflow

on:
  push:
    branches:
      - main  # Triggers workflow on push to main

jobs:
  use-secret:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use GitHub Secret
        env:
          MY_SECRET: ${{ secrets.SECRET }}  # Using the secret securely
        run: |
          if [ -z "$MY_SECRET" ]; then
            echo "Secret is not set properly!"
            exit 1
          else
            echo "Secret is set correctly but will not be printed!"
          fi

